services:

  sftp:
    image: atmoz/sftp;alpine
    restart: always
    volumes:
      - ./users.conf:/etc/sftp/users.conf:ro
      - ./keys/trivoallan.pub:/home/wordpress/.ssh/keys/trivoallan.pub:ro
      - /mnt/superlarsen/wordpress/wp:/home/wordpress/superlarsen.fr
    networks:
      - caddy
      - default
    labels:
      caddy: sftp.superlarsen.fr
      caddy.reverse_proxy: "{{upstreams 22}}"

networks:
  caddy:
    external: true