services:

  sftp:
    image: atmoz/sftp:alpine
    restart: always
    ports:
      - "2222:22"
    volumes:
      - ./users.conf:/etc/sftp/users.conf:ro
      - ./keys/trivoallan.pub:/home/wordpress/.ssh/keys/trivoallan.pub:ro
      - /mnt/superlarsen/wordpress/wp:/home/wordpress/superlarsen.fr
    networks:
      - caddy
      - default

networks:
  caddy:
    external: true