services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-exampleuser}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-examplepass}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-exampledb}
    volumes:
      - /mnt/superlarsen/wordpress/wp:/var/www/html
    networks:
      - caddy
      - default
    labels:
      caddy: www.superlarsen.fr
      caddy.reverse_proxy: "{{upstreams 80}}"
      stack-back.volumes: true


  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-exampledb}
      MYSQL_USER: ${MYSQL_USER:-exampleuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-examplepass}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /mnt/superlarsen/wordpress/db:/var/lib/mysql
    labels:
      stack-back.mysql: true

  backup:
    image: ghcr.io/lawndoc/stack-back:1.4.5
    env_file: .env
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./cache:/cache

networks:
  caddy:
    external: true
  smtp:
    external: true