services:
  app:
    image: castopod/castopod:1.13.4
    volumes:
      - /mnt/superlarsen/castopod/media:/var/www/castopod/public/media
    networks:
      - castopod-app
      - castopod-db
      - caddy
    restart: unless-stopped
    env_file: .env
    labels:
      caddy: castopod.superlarsen.fr
      caddy.reverse_proxy: "{{upstreams 8000}}"
      stack-back.volumes: true

  mariadb:
    image: mariadb:10.5
    networks:
      - castopod-db
    volumes:
      - /mnt/superlarsen/castopod/db:/var/lib/mysql
    labels:
      stack-back.mariadb: true
    restart: unless-stopped
    env_file: .env

  redis:
    image: redis:7.0-alpine
    command: --requirepass changeme
    env_file: .env
    volumes:
      - /mnt/superlarsen/castopod/cache:/data
    networks:
      - castopod-app
    restart: unless-stopped

  backup:
    image: ghcr.io/lawndoc/stack-back:v1.4.5
    env_file: .env
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./cache:/cache
    networks:
      - castopod-db

networks:
  castopod-app:
  castopod-db:
  caddy:
    external: true
  smtp:
    external: true